### ISSUE TITLE
OAuth integration fails

### ISSUE THREAD

**Issue by nebulade** [cloudron-io/wordpress-app#2]
The Oauth initiation route is not on the wordpress domain.

eg.
https://blog-berlin.cloudron.me/api/v1/oauth/dialog/authorize?response_type=code&client_id=cid-275b83d4-590b-46bc-8d69-838444f0163d&scope=profile&state=565b3164bc06c6.36859675&redirect_uri=https%3A%2F%2Fblog-berlin.cloudron.me%2F

**Comment by gramakri** [comment]
We now use ldap
